### ISSUE TITLE
Màn hình learn (Học chi tiết từ vựng)

### ISSUE THREAD

**Issue by FCBTruong** [FCBTruong/INT3120-2-2020#11]
Màn hình để học từ vựng đó(Từ, phát âm, định nghĩa, ví dụ ...).

**Comment by Trinh67** [comment]
Mà hình từ: b164aa3 ; Load ảnh và audio: f25992d ; reponsive: 1e77fc0

**Comment by Trinh67** [comment]
afd8fd7

**Comment by Trinh67** [comment]
Done
