### ISSUE TITLE
Màn hình tìm kiếm

### ISSUE THREAD

**Issue by FCBTruong** [FCBTruong/INT3120-2-2020#16]
Nhập input từ người dùng.

**Comment by NAT1804** [comment]
Hộp tìm kiếm có chuyển động phóng to thu nhỏ như vậy có hợp lý ko?

**Comment by FCBTruong** [comment]
Thấy hơi kỳ ,vì trước đó có cái button tìm kiếm r

**Comment by FCBTruong** [comment]
À mà cái search screen nó có cái thanh menu bottom đấy ,tại vì lần trc thử test chuyển screen

**Comment by NAT1804** [comment]
ok t sẽ thêm menu bottom và để hộp tìm kiếm cố định.

**Comment by FCBTruong** [comment]
Cái bottom menu là tự nó có
