### ISSUE TITLE
Không truy vấn được vào bảng images trong database.

### ISSUE THREAD

**Issue by NAT1804** [FCBTruong/INT3120-2-2020#36]
### Trong file database_local_helper.dart
- Đã khai báo tên bảng, tên cột.
![image](https://user-images.githubusercontent.com/51477539/96153986-86422880-0f38-11eb-8063-5451b2d372ea.png)
- Tạo câu truy vấn gọi dữ liệu
![image](https://user-images.githubusercontent.com/51477539/96154416-f94b9f00-0f38-11eb-9508-72ba76c2a1b5.png)
### Trong file main.dart
- Gọi hàm truy vấn
![image](https://user-images.githubusercontent.com/51477539/96154360-e769fc00-0f38-11eb-9855-4cdcca0346be.png)

### Gặp lỗi như ảnh dưới
![image](https://user-images.githubusercontent.com/51477539/96154591-2dbf5b00-0f39-11eb-9335-dc22ff7cf9ef.png)

**Comment by FCBTruong** [comment]
Chắc push code lên check xem, truy vấn trên sqlite vẫn chạy đc.

**Comment by FCBTruong** [comment]
Có thể do bản trên đt nó vẫn lưu db cũ, thử gỡ bản cài đặt trên điện thoại rồi cài lại xem

**Comment by NAT1804** [comment]
Vấn đề đã được giải quyết!
